export const searchTypes = {
    TOGGLE_SELL_TYPE: 'TOGGLE_SELL_TYPE',
    SET_SEARCH_PLACE: 'SET_SEARCH_PLACE',
    SET_FIXED_SEARCH_AMOUNT: 'SET_FIXED_SEARCH_AMOUNT',
    SET_MIN_SEARCH_AMOUNT: 'SET_MIN_SEARCH_AMOUNT',
    SET_MAX_SEARCH_AMOUNT: 'SET_MAX_SEARCH_AMOUNT',
    UPDATE_SEARCH_TYPE: 'UPDATE_SEARCH_TYPE',
    SET_BEDROOMS: 'SET_BEDROOMS',
    SET_BATHROOMS: 'SET_BATHROOMS',
}