export const searchTypes = {
  SET_SEARCH_NAME: "SET_SEARCH_NAME",
  SET_SEARCH_PLACE: "SET_SEARCH_PLACE",
  SET_FIXED_SEARCH_AMOUNT: "SET_FIXED_SEARCH_AMOUNT",
  SET_MIN_SEARCH_AMOUNT: "SET_MIN_SEARCH_AMOUNT",
  SET_MAX_SEARCH_AMOUNT: "SET_MAX_SEARCH_AMOUNT",
  SET_SEARCH_RENTAL_TYPES: "SET_SEARCH_RENTAL_TYPES",
  SET_BEDROOMS: "SET_BEDROOMS",
  SET_BATHROOMS: "SET_BATHROOMS",
};
