export const capitalizeFirstLetter = string => {
    return string.charAt(0).toUpperCase() + string.slice(1);
}

export const places = [
    'Akwa, Douala',
    'Beedi, Douala',
    'Bali, Douala',
    'Bepanda, Douala',
    'Bessengue, Douala',
    'Bonaberie, Douala',
    'Bonamoussadi, Douala',
    'Bonanjo, Douala',
    'Bonapriso, Douala',
    'Citée des palmiers, Douala',
    'Deïdo, Douala',
    'Denver, Santa Barbara',
    'Hopital general, Douala',
    'Kotto, Douala',
    'Logbessou, Douala',
    'Logpom, Douala',
    'Makepe, Douala',
    'New Bell, Douala',
    'Ndogbong, Douala',
    'Ndokoti, Douala',
    'Biyem-Assi, Yaoundé',
    'Cité Verte, Yaoundé',
    'Efoulan, Yaoundé',
    'Madagascar, Yaoundé',
    'Messa, Yaoundé',
    'Mvog-Betsi, Yaoundé',
    'Ngoa Ekélé, Yaoundé',
    'Nkom kana, Yaoundé',
    'Nsimeyong, Yaoundé',
    'Ntaba, Yaoundé',
    'Obili, Yaoundé',
    'Obobogo, Yaoundé',
    'Olezoa, Yaoundé',
    'Odza, Yaoundé',
    'Tsinga, Yaoundé',
]